config/routes.rb
RedditClone::Application.routes.draw do
  resources :users
  resource :session
  resources :subs
  resources :links do
    get "upvote", controller: :links
    get "downvote", controller: :links
  end
end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id             :integer          not null, primary key
#  contributor_id :integer
#  title          :string(255)      not null
#  url            :string(255)
#  body           :text
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Link < ActiveRecord::Base
  attr_accessible :body, :contributor_id, :title, :url, :sub_ids
  validates :title, presence: true

  belongs_to :contributor,
  class_name: "User"

  has_many :link_subs

  has_many :subs,
  through: :link_subs,
  source: :sub

  has_many :votes,
  class_name: "UserVote"

  def net_votes
    self.votes.sum(:vote)
  end


end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  include LinksHelper

  before_filter :ensure_link_contributor!, only: [:edit, :update]
  before_filter :ensure_deletion_capabilities, only: [:destroy]

  def new
    @link = Link.new
    @subs = Sub.includes(:links).all
  end

  def create
    @link = Link.new(params[:link])
    @link.contributor_id = current_user.id

    if @link.save
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      @subs = Sub.all
      render :new
    end
  end

  def show
    @link = Link.find(params[:id])
    render :show
  end

  def edit
    @subs = Sub.includes(:links).all
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update_attributes(params[:link])
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      @subs = Sub.all
      render :edit
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to subs_url
  end

  def upvote
    vote = UserVote.find_by_voter_id_and_link_id(current_user.id, params[:link_id])
    unless vote
      vote = UserVote.new(voter_id: current_user.id, link_id: params[:link_id], vote: 1)
      vote.save!
    else
      vote.update_attributes!(vote: 1)
    end
    redirect_to link_url(params[:link_id])
  end

  def downvote
    vote = UserVote.find_by_voter_id_and_link_id(current_user.id, params[:link_id])
    unless vote
      vote = UserVote.new(voter_id: current_user.id, link_id: params[:link_id], vote: -1)
      vote.save!
    else
      vote.update_attributes!(vote: -1)
    end
    redirect_to link_url(params[:link_id])
  end

  private

  def ensure_deletion_capabilities
    redirect_to link_url(@link) unless link_contributor? || moderator?
  end

  def ensure_link_contributor!
    @link = Link.find(params[:id])
    redirect_to link_url(@link) unless link_contributor?
  end

end

app/helpers/links_helper.rb
module LinksHelper

  def link_contributor?
    @link = Link.find(params[:id])
    current_user.id == @link.contributor_id
  end

  def link_moderator?
    @link = Link.find(params[:id])
    @link.subs.any? {|sub| sub.moderator_id == current_user.id }
  end
end

app/views/links/_form.html.erb
<form action="<%= path %>" method="post">
  <% if link.persisted? %>
    <input type="hidden" name="_method" value="PUT">
  <% end %>
  <%= auth_token %>

  <label>Title
  <input type="text" name="link[title]" value=<%= link.title %>></label>
  <br>
  <br>
  <label>URL
  <input type="text" name="link[url]" value=<%= link.url %>></label>
    <br>
    <br>
    <label>Body
    <input type="text" name="link[body]" value="<%= link.body %>"></label>
    <br>

    <input type="hidden" name="link[sub_ids][]" value="">
    Subs:<br>
    <% @subs.each do |sub| %>
    <label><input type="checkbox" name="link[sub_ids][]" value="<%= sub.id %>"
      <%= sub.links.include?(link) ? "checked" : "" %>
      ><%= sub.name %></label><br>
    <% end %>
    <input type="submit">

</form>

app/views/links/_link_view.html.erb
<h3><%= link_to link.title, link_url(link) %></h3>
<p>posted by: <%= link.contributor.username %></p>
<%= "url: #{link.url}" if link.url %>
<%= "body: #{link.body}" if link.body %>

app/views/links/edit.html.erb
<h1>Edit Link</h1>

<%= render "form", link: @link, subs: @subs, path: link_url(@link) %>

app/views/links/new.html.erb
<!--
#  id             :integer          not null, primary key
#  contributor_id :integer
#  title          :string(255)      not null
#  url            :string(255)
#  body           :text
#  created_at     :datetime         not null
#  updated_at     :datetime         not null-->
<h1> Create New Link</h1>


<%= render "form", link: @link, subs: @subs, path: links_url %>

app/views/links/show.html.erb
<h1><%= @link.title %></h1>
votes: <%= @link.net_votes %>
<br>
<%= render "link_view", link: @link %>
<br>
<% if link_contributor? %>
  <%= link_to "Edit Link", edit_link_url(@link) %>
<% end %>

<% if link_contributor? || link_moderator? %>
<%= button_to "Delete Link", link_url(@link), method: :delete %>
<% end %>