config/routes.rb
RedditClone::Application.routes.draw do
  resources :users
  resource :session
  resources :subs
  resources :links do
    get "upvote", controller: :links
    get "downvote", controller: :links
  end
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  name         :string(255)      not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  attr_accessible :moderator_id, :name

  belongs_to :moderator,
  class_name: "User"

  has_many :link_subs

  has_many :links,
    through: :link_subs,
    source: :link

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_filter :ensure_logged_in!, only: [:new, :create]
  before_filter :ensure_moderator!, only: [:edit, :update, :destroy]

  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new

    5.times do
      @sub.links.build
    end
  end

  def create
    @sub = Sub.new(params[:sub])
    @sub.moderator_id = current_user.id
    valid_link_params = params[:link].values.reject { |link| link["title"].empty? }
    @sub.links.new(valid_link_params)

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.includes(links: :contributor).find(params[:id])
    @links = @sub.links
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update_attributes(params[:sub])
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  private

  def ensure_moderator!
    @sub = Sub.find(params[:id])
    redirect_to sub_url(@sub) unless current_user.id == @sub.moderator_id
  end
end

app/helpers/subs_helper.rb
module SubsHelper

  def subs_moderator?
    @sub = Sub.find(params[:id])
    current_user.id == @sub.moderator.id
  end
end

app/views/subs/edit.html.erb
<h1> Edit Sub</h1>
<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="put">
  <%= auth_token %>

  <label>Sub Name<input type="text" name="sub[name]" value="<%= @sub.name %>">
  </label>

  <input type="submit" value="Edit sub">

</form>

app/views/subs/index.html.erb
<h1>KATIE'S REDDIT SUBS -- $5 FOOT LONGS</h1>
<ul>
<% @subs.each do |sub| %>
<li><%= link_to sub.name, sub_url(sub) %>
</li>
<% end %>
</ul>

app/views/subs/new.html.erb
<h1> Create Sub</h1>
<form action="<%= subs_url %>" method="post">
  <%= auth_token %>

  <label>Sub Name<input type="text" name="sub[name]" value="<%= @sub.name %>">
  </label>

  <input type="hidden" name="sub[moderator_id]" value="<%= current_user.id %>">

  <h3> Add Links </h3>
  <% @sub.links.each_with_index do |link,n| %>
  <h4>Link <%= n+1 %></h4>
  <label>Title
  <input type="text" name="link[<%= link.object_id %>][title]" value="<%= link.title %>">
  </label><br>

  <label>URL (optional)
  <input type="text" name="link[<%= link.object_id %>][url]" value="<%= link.url %>">
  </label><br>

  <label>Body (optional)
  <input type="text" name="link[<%= link.object_id %>][body]" value="<%= link.body %>">
  </label><br>

  <input type="hidden" name="link[<%= link.object_id %>][contributor_id]" value="<%= current_user.id %>">

  <% end %>

  <input type="submit" value="Create sub">

</form>

app/views/subs/show.html.erb
<h1><%= @sub.name %></h1>
<% if subs_moderator? %>
<%= link_to "Edit sub", edit_sub_url(@sub) %> | <%= button_to "Delete sub", sub_url(@sub), method: :delete %>
<% end %>

<p>moderated by <%= @sub.moderator.username %></p>
<ul>
  <% @links.each do |link| %>
  <li><%= render "links/link_view", link: link %>
    <%= button_to "Remove link", link_url(link), method: :delete if subs_moderator? %>
  </li>
  <% end %>
</ul>